[build]
  command = "npm run build"
  publish = "out"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/fetch-image"
  to = "/.netlify/functions/fetch-image"
  status = 200

[[redirects]]
  from = "/oauth-status"
  to = "/.netlify/functions/oauth-status"
  status = 200

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/callback"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
